# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e59818dad6a2bdfef573fe29410731cd05b25b14e2ca7b7e78bbbb47e94520e039c292dd6ae932abb35a66742910681624fa6ff29d0c26817b0aa4fa6cde815

test:
  secret_key_base: 18cab3d6b8671334be4bb2911808611147b294548a99a5101c354cf1ca2445b8908c6cf7152a1d3c0c32e7dc7fb961189be30f90df7bd8a71742d7de4401ffab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
